### ISSUE TITLE
小程序有上线吗？想瞅瞅

### ISSUE THREAD

**Issue by talmudmaster** [luzhixing12345/Campus-Map-Digital-Platform#1]

**Comment by luzhixing12345** [comment]
这个项目用到了云开发的数据库和存储，现在微信的云开发开始收费了，每个月39吃不消，大概也不会上线
软工的小组作业，做的一般，课程结束了应该也就不维护了
感谢您的关注

**Comment by talmudmaster** [comment]
大佬挺厉害的
云开发确实贵，难为大伙了
我是软工专业的，最近做毕设，感觉学校啥都教，但啥都学了个寂寞，哈哈哈
毕设的小程序我都打算自己写数据库了。不指望老师给我报销费用，哈哈哈
&nbsp;


talmudmaster
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月31日(星期一) 下午4:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [luzhixing12345/Campus-Map-Digital-Platform] 小程序有上线吗？想瞅瞅 (Issue #1)





 
这个项目用到了云开发的数据库和存储，现在微信的云开发开始收费了，每个月39吃不消，大概也不会上线
 软工的小组作业，做的一般，课程结束了应该也就不维护了
 感谢您的关注
